# Generated by Django 5.2.8 on 2025-11-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('species', models.CharField(max_length=10)),
                ('scientific_name', models.CharField(max_length=20)),
                ('habitat', models.CharField(max_length=40)),
                ('age', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Caretakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('experiance_years', models.CharField(max_length=10)),
                ('shift_time', models.TimeField()),
                ('assigned_animals', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('donated_amount', models.FloatField(max_length=10, unique=True)),
                ('date_donated', models.DateField()),
                ('email', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
